### PR TITLE
optional redirect

### PR DESCRIPTION
**Pull request by i8ramin**
Added an optional param `redirect` that will do the following:
- disable the default redirect from `/path` to `/en/path`
- disable generating of `/en/*` pages

Motivation here is that for the *default* language (ie, `en`), we want the site to behave as normal. Without any language specific paths. But for all other supported/available languages, we want to generate those pages.

One caveat here is that the _redirect_ logic is now disabled and it is up to the author to determine when to redirect a user to the appropriate language based on their browser settings. We typically handle this at the Edge (ie, Fastly VCL) using geo-targeting and redirects.

### CODE REVIEW

**Comment by i8ramin** [comment]
related issue -- https://github.com/ikhudo/gatsby-i18n-plugin/issues/4

**Comment by i8ramin** [comment]
Wasn't getting much response, so decided to fork the project and continue work on it to fit our needs

**Comment by DDeme** [comment]
Is there any updates on this topic ?

**Comment by silverveskilt** [comment]
> @i8ramin is your fork available somewhere?

+1

**Comment by 5tormTrooper** [comment]
> > @i8ramin is your fork available somewhere?
> 
> +1

+1

**Comment by stormfar** [comment]
> > > @i8ramin is your fork available somewhere?
> > 
> > 
> > +1
> 
> +1
@i8ramin 🙏

**Comment by i8ramin** [comment]
hi @5tormTrooper, unfortunately I no longer have access to the fork/repo .. but the this closed PR has some of the logic needed to make this work .. look at this file specifically: 

https://github.com/ikhudo/gatsby-i18n-plugin/pull/5/files#diff-1962e97a9359cbf6f44c5e3d398ee95e

**Comment by stormfar** [comment]
Thanks for getting back. I'll check it out and post a new fork for anyone else who comes across this.

**Pull request closed without merging**
